apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestion-pipeline-config
  namespace: hadar
data:
  DEBUG: "false"
  LOG_LEVEL: INFO
  MQTT_BASE_TOPIC: zigbee2mqtt
  MQTT_HOST: MQTT_BROKER_HOST_OR_IP
  MQTT_PORT: "1883"
  QUEUE_MAX_COMMIT_SIZE: "40"

