apiVersion: v1
kind: Secret
metadata:
  name: ingestion-pipeline-creds
  namespace: hadar
type: Opaque
stringData:
  DATABASE_URL: postgresql+asyncpg://USER:PASSWORD@postgres.db.svc.cluster.local:5432/zigbee_db
  MQTT_USER: MQTT_USERNAME
  MQTT_PASS: MQTT_PASSWORD

