apiVersion: apps/v1
kind: Deployment
metadata:
  name: scoring-pipeline
  namespace: hadar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scoring-pipeline
  template:
    metadata:
      labels:
        app: scoring-pipeline
    spec:
      containers:
        - name: scoring-pipeline
          image: haka9670/scoring-pipeline:65708ed
          imagePullPolicy: IfNotPresent
          command:
            - python
            - main.py
          envFrom:
            - secretRef:
                name: isolation-forest-creds
            - configMapRef:
                name: scoring-pipeline-config
          volumeMounts:
            - name: hadar-data
              mountPath: /mnt/hadar-data
              subPath: scoring-pipeline
            - name: hadar-data
              mountPath: /mnt/hadar-model-data
              subPath: isolation-forest
              readOnly: true
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: hadar-data
          persistentVolumeClaim:
            claimName: hadar-data-pvc
