apiVersion: v1
kind: Service
metadata:
  name: hadar-ui
  namespace: hadar
spec:
  type: NodePort
  selector:
    app: hadar-ui
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080   # http://<node-ip>:30080
