apiVersion: v1
kind: Service
metadata:
  name: hadar-api
  namespace: hadar
spec:
  type: NodePort
  selector:
    app: hadar-api
  ports:
    - name: http
      port: 8000
      targetPort: http
      nodePort: 30800
      protocol: TCP
